theme: jekyll-theme-cayman
process:
  twig: true
  
title: Obedience Interland 
description: KC De Kempen - 17 juli 2022

km_nl: Monique Barten &amp; Dirk Belder
km_de: Sabine Richarz &amp; Gerlinde Dobler
prijs: €&nbsp;19,-
